services:
  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    # Não exponha diretamente a porta 80 - o NGINX vai fazer isso
    # ports:
    #   - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - frontend_network

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt           # Montar certificados SSL no container
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot-www:/var/www/letsencrypt
    depends_on:
      - frontend
    networks:
      - frontend_network

  certbot:
    image: certbot/certbot
    container_name: frontend_certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./certbot-www:/var/www/letsencrypt
    depends_on:
      - nginx
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :;
      do certbot renew --webroot -w /var/www/letsencrypt --quiet;
      sleep 12h & wait $${!};
      done'

networks:
  frontend_network:
    driver: bridge