services:
  frontend:
    build: .
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-www:/var/www/letsencrypt
    environment:
      - VITE_API_URL=${VITE_API_URL}

networks:
  default:
    name: frontend_network
